import {
  Organization,
  Branch,
  Professional,
  Service,
  Resource,
  WorkingHour,
  Customer,
  Appointment,
  Product,
  StockMovement,
  CashSession,
  Sale,
  AuditEvent,
  Profile,
  OrganizationMember,
} from '../../types/database.types';

// Helper to create dates today or offset at given hour and minute
function getTodaySlot(hour: number, minute: number, dayOffset = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

// 1. ÚNICA ORGANIZACIÓN: Peluquería & Barbería Estilo
export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-peluqueria',
    name: 'Peluquería & Barbería Estilo',
    slug: 'peluqueria-estilo',
    industry: 'salon',
    primary_color: '#5E836F',
    currency: 'ARS',
    default_timezone: 'America/Argentina/Buenos_Aires',
    contact_email: 'contacto@peluqueriaestilo.com',
    contact_phone: '+54 11 4567-8901',
    is_active: true,
    account_config: {
      plan_tier: 'growth',
      tier_name: 'Plan Comercial',
      delegation_mode: 'full',
      allowed_roles: ['owner', 'admin', 'branch_manager', 'receptionist', 'professional', 'cashier'],
      max_branches: 1,
      max_professionals: 5,
      allow_role_delegation: true,
      enabled_modules: {
        inventory: true,
        sales_pos: true,
        audit: true,
        confidential_notes: false,
        deposits: true,
        multi_service: true,
        client_merging: true,
      },
      subscription_type: 'vitalicio',
      subscription_status: 'lifetime',
      subscription_started_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      subscription_expires_at: null,
      subscription_label: 'Socio Vitalicio (Sin Vencimiento)',
      owner_username: 'peluqueria',
      owner_password: 'password123',
      notes: 'Peluquería & Barbería Estilo con turnos, clientes y caja cargados.',
    },
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
];

// 2. SUCURSAL
export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-central',
    organization_id: 'org-peluqueria',
    name: 'Sucursal Central',
    slug: 'central',
    address: 'Av. Corrientes 1450, CABA',
    city: 'Buenos Aires',
    phone: '+54 11 4567-8901',
    timezone: 'America/Argentina/Buenos_Aires',
    currency: 'ARS',
    min_advance_minutes: 60,
    max_advance_days: 30,
    cancel_window_hours: 12,
    deposit_required_pct: 0,
    requires_approval: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

// 3. PROFESIONALES DE LA PELUQUERÍA
export const INITIAL_PROFESSIONALS: Professional[] = [
  {
    id: 'prof-martin',
    organization_id: 'org-peluqueria',
    display_name: 'Martín Gómez',
    specialty: 'Estilista Principal & Barbero',
    bio: 'Más de 8 años de experiencia en cortes clásicos, degradados y peinados de tendencia.',
    avatar_url: '',
    color_tag: '#5E836F',
    is_public: true,
    is_active: true,
    commission_rate_pct: 40,
    branch_ids: ['branch-central'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prof-lucas',
    organization_id: 'org-peluqueria',
    display_name: 'Lucas Silva',
    specialty: 'Colorista & Tratamientos',
    bio: 'Especialista en colorimetría capilar, iluminación y cuidado capilar intensivo.',
    avatar_url: '',
    color_tag: '#C49A45',
    is_public: true,
    is_active: true,
    commission_rate_pct: 35,
    branch_ids: ['branch-central'],
    created_at: new Date().toISOString(),
  },
];

// 4. SERVICIOS DE LA PELUQUERÍA
export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv-corte-clasico',
    organization_id: 'org-peluqueria',
    name: 'Corte de Cabello Estilo',
    description: 'Corte personalizado con tijera o máquina, lavado y peinado final.',
    category: 'Corte & Peinado',
    duration_minutes: 45,
    prep_buffer_minutes: 0,
    clean_buffer_minutes: 5,
    price: 12000,
    deposit_amount: 0,
    tax_rate_pct: 21,
    is_public: true,
    is_active: true,
    requires_resource: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-corte-barba',
    organization_id: 'org-peluqueria',
    name: 'Corte de Cabello + Barba Premium',
    description: 'Servicio completo de corte, perfilado de barba a navaja y toalla caliente.',
    category: 'Combo',
    duration_minutes: 60,
    prep_buffer_minutes: 0,
    clean_buffer_minutes: 5,
    price: 18000,
    deposit_amount: 0,
    tax_rate_pct: 21,
    is_public: true,
    is_active: true,
    requires_resource: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-barba',
    organization_id: 'org-peluqueria',
    name: 'Perfilado y Arreglo de Barba',
    description: 'Afeitado tradicional con toalla caliente, aceites aromáticos y bálsamo hidratante.',
    category: 'Barbería',
    duration_minutes: 30,
    prep_buffer_minutes: 0,
    clean_buffer_minutes: 5,
    price: 8000,
    deposit_amount: 0,
    tax_rate_pct: 21,
    is_public: true,
    is_active: true,
    requires_resource: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-coloracion',
    organization_id: 'org-peluqueria',
    name: 'Coloración & Mechas Balayage',
    description: 'Diseño de color completo, decoloración cuidada y tratamiento de brillo.',
    category: 'Color',
    duration_minutes: 120,
    prep_buffer_minutes: 0,
    clean_buffer_minutes: 10,
    price: 35000,
    deposit_amount: 5000,
    tax_rate_pct: 21,
    is_public: true,
    is_active: true,
    requires_resource: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-lavado-nutricion',
    organization_id: 'org-peluqueria',
    name: 'Baño de Crema & Nutrición Profunda',
    description: 'Lavado con masaje capilar, nutrición intensiva y secado modelado.',
    category: 'Tratamientos',
    duration_minutes: 40,
    prep_buffer_minutes: 0,
    clean_buffer_minutes: 5,
    price: 14000,
    deposit_amount: 0,
    tax_rate_pct: 21,
    is_public: true,
    is_active: true,
    requires_resource: true,
    created_at: new Date().toISOString(),
  },
];

// 5. RECURSOS / SILLONES
export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 'res-sillon-1',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    name: 'Sillón Principal 01',
    resource_type: 'chair',
    capacity: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'res-sillon-2',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    name: 'Sillón Estilo 02',
    resource_type: 'chair',
    capacity: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

// 6. HORARIOS DE ATENCIÓN (Lunes a Sábado de 09:00 a 20:00)
export const INITIAL_WORKING_HOURS: WorkingHour[] = [
  ...[1, 2, 3, 4, 5, 6].map((dayOfWeek) => ({
    id: `wh-central-${dayOfWeek}`,
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    day_of_week: dayOfWeek,
    open_time: '09:00',
    close_time: '20:00',
    is_enabled: true,
  })),
  {
    id: 'wh-central-0',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    day_of_week: 0,
    open_time: '09:00',
    close_time: '14:00',
    is_enabled: false,
  },
];

// 7. CLIENTES CARGADOS
export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    organization_id: 'org-peluqueria',
    full_name: 'Carlos Gómez',
    phone: '+54 11 5566-7788',
    email: 'carlos.gomez@gmail.com',
    notes: 'Cliente habitual. Prefiere degrade medio con navaja.',
    tags: ['habitual', 'vip'],
    is_blacklisted: false,
    total_appointments: 8,
    total_spent: 96000,
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'cust-2',
    organization_id: 'org-peluqueria',
    full_name: 'Julián Benítez',
    phone: '+54 11 4433-2211',
    email: 'julian.b@hotmail.com',
    notes: 'Corte clásico con tijera y toalla caliente para barba.',
    tags: ['puntual'],
    is_blacklisted: false,
    total_appointments: 4,
    total_spent: 72000,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'cust-3',
    organization_id: 'org-peluqueria',
    full_name: 'Florencia Vega',
    phone: '+54 11 6789-1234',
    email: 'flor.vega@yahoo.com',
    notes: 'Tratamientos de mechas y nutrición.',
    tags: ['coloración'],
    is_blacklisted: false,
    total_appointments: 3,
    total_spent: 105000,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'cust-4',
    organization_id: 'org-peluqueria',
    full_name: 'Rodrigo Morales',
    phone: '+54 11 3214-5678',
    email: 'rodrigo.m@gmail.com',
    notes: 'Viene cada 15 días para mantener el fade.',
    tags: ['frecuente'],
    is_blacklisted: false,
    total_appointments: 6,
    total_spent: 72000,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cust-5',
    organization_id: 'org-peluqueria',
    full_name: 'Matías Fernández',
    phone: '+54 11 9876-5432',
    email: 'matias.fer@gmail.com',
    notes: 'Turno reservado para mañana.',
    tags: ['nuevo'],
    is_blacklisted: false,
    total_appointments: 1,
    total_spent: 18000,
    created_at: new Date().toISOString(),
  },
];

// 8. TURNOS CARGADOS (Hoy y Mañana)
export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'appt-1',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    professional_id: 'prof-martin',
    customer_id: 'cust-1',
    status: 'completed',
    payment_status: 'paid',
    starts_at: getTodaySlot(10, 0),
    ends_at: getTodaySlot(10, 45),
    service_duration_minutes: 45,
    total_amount: 12000,
    deposit_amount: 0,
    customer_notes: 'Corte clásico con degrade medio.',
    booking_channel: 'admin_backoffice',
    management_token: 'tok-carlos-1111',
    management_token_expires_at: new Date(Date.now() + 30 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'appt-2',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    professional_id: 'prof-martin',
    customer_id: 'cust-2',
    status: 'in_progress',
    payment_status: 'pending',
    starts_at: getTodaySlot(11, 0),
    ends_at: getTodaySlot(12, 0),
    service_duration_minutes: 60,
    total_amount: 18000,
    deposit_amount: 0,
    customer_notes: 'Corte + Barba completa con toalla caliente.',
    booking_channel: 'public_web',
    management_token: 'tok-julian-2222',
    management_token_expires_at: new Date(Date.now() + 30 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'appt-3',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    professional_id: 'prof-lucas',
    customer_id: 'cust-3',
    status: 'confirmed',
    payment_status: 'paid',
    starts_at: getTodaySlot(14, 0),
    ends_at: getTodaySlot(16, 0),
    service_duration_minutes: 120,
    total_amount: 35000,
    deposit_amount: 5000,
    customer_notes: 'Coloración Balayage con tratamiento de brillo.',
    booking_channel: 'public_web',
    management_token: 'tok-flor-3333',
    management_token_expires_at: new Date(Date.now() + 30 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'appt-4',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    professional_id: 'prof-martin',
    customer_id: 'cust-4',
    status: 'confirmed',
    payment_status: 'pending',
    starts_at: getTodaySlot(16, 30),
    ends_at: getTodaySlot(17, 15),
    service_duration_minutes: 45,
    total_amount: 12000,
    deposit_amount: 0,
    customer_notes: 'Mantenimiento de fade con navaja.',
    booking_channel: 'admin_backoffice',
    management_token: 'tok-rodrigo-4444',
    management_token_expires_at: new Date(Date.now() + 30 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'appt-5',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    professional_id: 'prof-martin',
    customer_id: 'cust-5',
    status: 'confirmed',
    payment_status: 'pending',
    starts_at: getTodaySlot(10, 0, 1), // Mañana 10:00
    ends_at: getTodaySlot(11, 0, 1),
    service_duration_minutes: 60,
    total_amount: 18000,
    deposit_amount: 0,
    customer_notes: 'Turno para mañana temprano.',
    booking_channel: 'public_web',
    management_token: 'tok-matias-5555',
    management_token_expires_at: new Date(Date.now() + 30 * 86400000).toISOString(),
    created_at: new Date().toISOString(),
  },
];

// 9. PRODUCTOS Y STOCK
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-cera',
    organization_id: 'org-peluqueria',
    sku: 'EST-CERA-01',
    name: 'Pomada Matte Clay Extra Hold 100ml',
    category: 'Fijación',
    cost_price: 5500,
    sale_price: 11000,
    tax_rate_pct: 21,
    min_stock_alert: 5,
    is_active: true,
    current_stock: 18,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-shampoo',
    organization_id: 'org-peluqueria',
    sku: 'EST-SHAMP-02',
    name: 'Shampoo Revitalizante Capilar 250ml',
    category: 'Cuidado Capilar',
    cost_price: 7000,
    sale_price: 14500,
    tax_rate_pct: 21,
    min_stock_alert: 4,
    is_active: true,
    current_stock: 12,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-aceite',
    organization_id: 'org-peluqueria',
    sku: 'EST-BARB-03',
    name: 'Aceite Hidratante para Barba 30ml',
    category: 'Barbería',
    cost_price: 4500,
    sale_price: 9500,
    tax_rate_pct: 21,
    min_stock_alert: 3,
    is_active: true,
    current_stock: 9,
    created_at: new Date().toISOString(),
  },
];

// 10. MOVIMIENTOS DE STOCK
export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'mov-1',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    product_id: 'prod-cera',
    movement_type: 'purchase_in',
    quantity: 20,
    previous_stock: 0,
    new_stock: 20,
    reason: 'Ingreso inicial de stock',
    performed_by_name: 'Martín Gómez',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'mov-2',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    product_id: 'prod-cera',
    movement_type: 'sale_out',
    quantity: -2,
    previous_stock: 20,
    new_stock: 18,
    reason: 'Venta mostrador a cliente',
    performed_by_name: 'Martín Gómez',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

// 11. SESIONES DE CAJA
export const INITIAL_CASH_SESSIONS: CashSession[] = [
  {
    id: 'cash-ses-1',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    opened_by_name: 'Martín Gómez',
    opened_at: getTodaySlot(8, 45),
    initial_amount: 25000,
    status: 'open',
    notes: 'Caja del día abierta con fondo para cambio.',
  },
];

// 12. VENTAS REALIZADAS
export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-1',
    organization_id: 'org-peluqueria',
    branch_id: 'branch-central',
    cash_session_id: 'cash-ses-1',
    customer_id: 'cust-1',
    receipt_number: 'B001-000142',
    subtotal: 12000,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 12000,
    paid_amount: 12000,
    payment_status: 'paid',
    payment_method: 'cash',
    created_at: getTodaySlot(10, 45),
    items: [
      {
        id: 'item-1',
        sale_id: 'sale-1',
        description: 'Corte de Cabello Estilo (Carlos Gómez)',
        quantity: 1,
        unit_price: 12000,
        discount_rate_pct: 0,
        line_total: 12000,
      },
    ],
  },
];

// 13. AUDITORÍA
export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'aud-1',
    organization_id: 'org-peluqueria',
    user_name: 'Martín Gómez',
    action: 'cash_session.opened',
    resource_type: 'cash_sessions',
    resource_id: 'cash-ses-1',
    metadata: { initial_amount: 25000 },
    created_at: getTodaySlot(8, 45),
  },
  {
    id: 'aud-2',
    organization_id: 'org-peluqueria',
    user_name: 'Martín Gómez',
    action: 'appointment.completed',
    resource_type: 'appointments',
    resource_id: 'appt-1',
    metadata: { customer: 'Carlos Gómez', amount: 12000 },
    created_at: getTodaySlot(10, 45),
  },
];

// 14. PERFILES: EXACTAMENTE 2 USUARIOS (ADMIN Y PELUQUERÍA)
export const INITIAL_PROFILES: Profile[] = [
  // 1) Super Admin (Nosotros)
  {
    id: 'user-admin',
    username: 'admin',
    password: 'admin123',
    email: 'admin@turnopro.com',
    full_name: 'Administrador (Nosotros)',
    phone: '+54 11 9999-8888',
    is_superadmin: true,
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
  },
  // 2) Único Negocio de Prueba (Peluquería)
  {
    id: 'user-peluqueria',
    username: 'peluqueria',
    password: 'password123',
    email: 'contacto@peluqueriaestilo.com',
    full_name: 'Martín Gómez (Peluquería)',
    phone: '+54 11 4567-8901',
    is_superadmin: false,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
];

// 15. MEMBRESÍAS: EXACTAMENTE 1 MEMBRESÍA DE CLIENTE
export const INITIAL_MEMBERSHIPS: OrganizationMember[] = [
  {
    id: 'mem-peluqueria-1',
    organization_id: 'org-peluqueria',
    user_id: 'user-peluqueria',
    role: 'owner',
    is_active: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
];
